service: api-scraper
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    tableName: !Ref SearchesTable

plugins:
  - serverless-esbuild

package:
  individually: true

functions:
  RunAmazonScraper:
    handler: src/functions/runAmazonScraper/handler.main
    layers:
      - !Ref ChromiumLambdaLayer
    memorySize: 1024
    timeout: 30 # limite imposto pela AWS para endpoints
    events:
      - http:
          path: amazon/mais-vendidos
          method: get

layers:
  chromium:
    package:
      artifact: chromium/chromium.zip

custom:
  esbuild:
    exclude:
      - "@sparticuz/chromium"
    keepOutputDirectory: true

resources:
  Resources:
    SearchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: "S"
        KeySchema:
          - AttributeName: id
            KeyType: "HASH"
        TableName: api-scraper-searches
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
